# shellcheck disable=SC2034

PODKOP_XRAY_VERSION="__COMPILED_VERSION_VARIABLE__"
# In dev mode (not built via SDK), version stays as placeholder
# SDK build replaces __COMPILED_VERSION_VARIABLE__ via sed in Makefile
case "$PODKOP_XRAY_VERSION" in
*COMPILED*) PODKOP_XRAY_VERSION="0.26.3.27-dev" ;;
esac

## Common
PODKOP_XRAY_CONFIG="/etc/config/podkop-xray"
RESOLV_CONF="/etc/resolv.conf"
DNS_RESOLVERS="1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4 9.9.9.9 9.9.9.11 94.140.14.14 94.140.15.15 208.67.220.220 208.67.222.222 77.88.8.1 77.88.8.8"
TMP_XRAY_FOLDER="/tmp/xray"
TMP_GEOFILES_FOLDER="$TMP_XRAY_FOLDER/geofiles"
TMP_LISTS_FOLDER="$TMP_XRAY_FOLDER/lists"
JQ_REQUIRED_VERSION="1.7.1"
COREUTILS_BASE64_REQUIRED_VERSION="9.7"
RT_TABLE_NAME="podkop_xray"

## nft
NFT_TABLE_NAME="PodkopXrayTable"
NFT_LOCALV4_SET_NAME="localv4"
NFT_COMMON_SET_NAME="podkop_xray_subnets"
NFT_INTERFACE_SET_NAME="interfaces"
NFT_FAKEIP_MARK="0x00100000"
NFT_OUTBOUND_MARK="0xff"

## Xray
XRAY_REQUIRED_VERSION="26.3.27"
# DNS
XRAY_DNS_INBOUND_TAG="dns-in"
XRAY_DNS_INBOUND_ADDRESS="127.0.0.1"
XRAY_DNS_INBOUND_PORT=5300
# FakeDNS
XRAY_FAKEDNS_POOL="198.18.0.0/15"
XRAY_FAKEDNS_POOL_SIZE=65535
# Inbounds
XRAY_TPROXY_INBOUND_TAG="tproxy-in"
XRAY_TPROXY_INBOUND_ADDRESS="0.0.0.0"
XRAY_TPROXY_INBOUND_PORT=12345
# Outbounds
XRAY_DIRECT_OUTBOUND_TAG="direct"
XRAY_BLOCK_OUTBOUND_TAG="block"
XRAY_DNS_OUTBOUND_TAG="dns-out"
XRAY_PROXY_OUTBOUND_TAG="proxy"

## Geofiles
# Filtered geosite.dat (20 categories, ~5.6MB) built by CI from runetfreedom/russia-v2ray-rules-dat
GEOSITE_URL="https://github.com/skvarovski/russia-v2ray-rules-dat-small/releases/latest/download/geosite.dat"
# Filtered geoip.dat (11 categories, ~2MB) built by CI from runetfreedom/russia-blocked-geoip
GEOIP_URL="https://github.com/skvarovski/russia-v2ray-rules-dat-small/releases/latest/download/geoip.dat"
# Category list files (generated by CI alongside .dat files)
GEOSITE_CATEGORIES_URL="https://github.com/skvarovski/russia-v2ray-rules-dat-small/releases/latest/download/geosite_categories.txt"
GEOIP_CATEGORIES_URL="https://github.com/skvarovski/russia-v2ray-rules-dat-small/releases/latest/download/geoip_categories.txt"
# Fallback: GeoIP categories included in filtered geoip.dat (defined by CI filter-geoip.py)
GEOIP_CATEGORIES_FALLBACK="RU-BLOCKED RE-FILTER RU-BLOCKED-COMMUNITY TELEGRAM GOOGLE CLOUDFLARE RU RU-WHITELIST YANDEX DDOS-GUARD PRIVATE"
